// Defines the message contract for the KeyService.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: src/types/key/v1/key.proto

package keys_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicKeysPb represents the set of public keys for a user.
// This message is returned by the /api/keys/{userId} endpoint.
type PublicKeysPb struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The raw SPKI bytes of the public encryption key (RSA-OAEP).
	EncKey []byte `protobuf:"bytes,1,opt,name=enc_key,json=encKey,proto3" json:"enc_key,omitempty"`
	// The raw SPKI bytes of the public signing key (RSA-PSS).
	// This is mission-critical for the "Sealed Sender" model.
	SigKey        []byte `protobuf:"bytes,2,opt,name=sig_key,json=sigKey,proto3" json:"sig_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeysPb) Reset() {
	*x = PublicKeysPb{}
	mi := &file_src_types_key_v1_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeysPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeysPb) ProtoMessage() {}

func (x *PublicKeysPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_key_v1_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeysPb.ProtoReflect.Descriptor instead.
func (*PublicKeysPb) Descriptor() ([]byte, []int) {
	return file_src_types_key_v1_key_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKeysPb) GetEncKey() []byte {
	if x != nil {
		return x.EncKey
	}
	return nil
}

func (x *PublicKeysPb) GetSigKey() []byte {
	if x != nil {
		return x.SigKey
	}
	return nil
}

var File_src_types_key_v1_key_proto protoreflect.FileDescriptor

const file_src_types_key_v1_key_proto_rawDesc = "" +
	"\n" +
	"\x1asrc/types/key/v1/key.proto\x12\x11src.types.keys.v1\"@\n" +
	"\fPublicKeysPb\x12\x17\n" +
	"\aenc_key\x18\x01 \x01(\fR\x06encKey\x12\x17\n" +
	"\asig_key\x18\x02 \x01(\fR\x06sigKeyBAZ?github.com/tinywideclouds/gen-platform/go/types/keys/v1;keys_v1b\x06proto3"

var (
	file_src_types_key_v1_key_proto_rawDescOnce sync.Once
	file_src_types_key_v1_key_proto_rawDescData []byte
)

func file_src_types_key_v1_key_proto_rawDescGZIP() []byte {
	file_src_types_key_v1_key_proto_rawDescOnce.Do(func() {
		file_src_types_key_v1_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_key_v1_key_proto_rawDesc), len(file_src_types_key_v1_key_proto_rawDesc)))
	})
	return file_src_types_key_v1_key_proto_rawDescData
}

var file_src_types_key_v1_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_types_key_v1_key_proto_goTypes = []any{
	(*PublicKeysPb)(nil), // 0: src.types.keys.v1.PublicKeysPb
}
var file_src_types_key_v1_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_types_key_v1_key_proto_init() }
func file_src_types_key_v1_key_proto_init() {
	if File_src_types_key_v1_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_key_v1_key_proto_rawDesc), len(file_src_types_key_v1_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_key_v1_key_proto_goTypes,
		DependencyIndexes: file_src_types_key_v1_key_proto_depIdxs,
		MessageInfos:      file_src_types_key_v1_key_proto_msgTypes,
	}.Build()
	File_src_types_key_v1_key_proto = out.File
	file_src_types_key_v1_key_proto_goTypes = nil
	file_src_types_key_v1_key_proto_depIdxs = nil
}
