// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: src/types/net/v1/urn.proto

package sm_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UrnPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entityType,proto3" json:"entityType,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entityId,proto3" json:"entityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrnPb) Reset() {
	*x = UrnPb{}
	mi := &file_src_types_net_v1_urn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrnPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrnPb) ProtoMessage() {}

func (x *UrnPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_net_v1_urn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrnPb.ProtoReflect.Descriptor instead.
func (*UrnPb) Descriptor() ([]byte, []int) {
	return file_src_types_net_v1_urn_proto_rawDescGZIP(), []int{0}
}

func (x *UrnPb) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UrnPb) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *UrnPb) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

var File_src_types_net_v1_urn_proto protoreflect.FileDescriptor

const file_src_types_net_v1_urn_proto_rawDesc = "" +
	"\n" +
	"\x1asrc/types/net/v1/urn.proto\x12\ftypes.net.v1\"a\n" +
	"\x05UrnPb\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"entityType\x18\x02 \x01(\tR\n" +
	"entityType\x12\x1a\n" +
	"\bentityId\x18\x03 \x01(\tR\bentityIdB8Z6github.com/tinywideclouds/gen-platform/go/net/v1;sm_v1b\x06proto3"

var (
	file_src_types_net_v1_urn_proto_rawDescOnce sync.Once
	file_src_types_net_v1_urn_proto_rawDescData []byte
)

func file_src_types_net_v1_urn_proto_rawDescGZIP() []byte {
	file_src_types_net_v1_urn_proto_rawDescOnce.Do(func() {
		file_src_types_net_v1_urn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_net_v1_urn_proto_rawDesc), len(file_src_types_net_v1_urn_proto_rawDesc)))
	})
	return file_src_types_net_v1_urn_proto_rawDescData
}

var file_src_types_net_v1_urn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_types_net_v1_urn_proto_goTypes = []any{
	(*UrnPb)(nil), // 0: types.net.v1.UrnPb
}
var file_src_types_net_v1_urn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_types_net_v1_urn_proto_init() }
func file_src_types_net_v1_urn_proto_init() {
	if File_src_types_net_v1_urn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_net_v1_urn_proto_rawDesc), len(file_src_types_net_v1_urn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_net_v1_urn_proto_goTypes,
		DependencyIndexes: file_src_types_net_v1_urn_proto_depIdxs,
		MessageInfos:      file_src_types_net_v1_urn_proto_msgTypes,
	}.Build()
	File_src_types_net_v1_urn_proto = out.File
	file_src_types_net_v1_urn_proto_goTypes = nil
	file_src_types_net_v1_urn_proto_depIdxs = nil
}
