// Defines the message contract for sending push notification requests.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: src/types/notification/v1/notification.proto

package notification_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebPushSubscriptionPb models the standard W3C Push Subscription structure.
// This handles the "huge JSON" explicitly instead of stringifying it.
type WebPushSubscriptionPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	P256Dh        string                 `protobuf:"bytes,2,opt,name=p256dh,proto3" json:"p256dh,omitempty"`
	Auth          string                 `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPushSubscriptionPb) Reset() {
	*x = WebPushSubscriptionPb{}
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPushSubscriptionPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPushSubscriptionPb) ProtoMessage() {}

func (x *WebPushSubscriptionPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPushSubscriptionPb.ProtoReflect.Descriptor instead.
func (*WebPushSubscriptionPb) Descriptor() ([]byte, []int) {
	return file_src_types_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *WebPushSubscriptionPb) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WebPushSubscriptionPb) GetP256Dh() string {
	if x != nil {
		return x.P256Dh
	}
	return ""
}

func (x *WebPushSubscriptionPb) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

// 2. The Service-to-Service Request
// No tokens here. The service looks them up.
type NotificationRequestPb struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RecipientId   string                         `protobuf:"bytes,1,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"` // e.g. "urn:user:123"
	Content       *NotificationRequestPb_Content `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	DataPayload   map[string]string              `protobuf:"bytes,3,rep,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequestPb) Reset() {
	*x = NotificationRequestPb{}
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequestPb) ProtoMessage() {}

func (x *NotificationRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequestPb.ProtoReflect.Descriptor instead.
func (*NotificationRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationRequestPb) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *NotificationRequestPb) GetContent() *NotificationRequestPb_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *NotificationRequestPb) GetDataPayload() map[string]string {
	if x != nil {
		return x.DataPayload
	}
	return nil
}

// DeviceTokenPb represents a single push notification token for a user's device.
type DeviceTokenPb struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The platform-specific token string from the device.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// The platform identifier, e.g., "ios", "android".
	Platform      string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTokenPb) Reset() {
	*x = DeviceTokenPb{}
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTokenPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTokenPb) ProtoMessage() {}

func (x *DeviceTokenPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTokenPb.ProtoReflect.Descriptor instead.
func (*DeviceTokenPb) Descriptor() ([]byte, []int) {
	return file_src_types_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceTokenPb) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeviceTokenPb) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type NotificationRequestPb_Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Sound         string                 `protobuf:"bytes,3,opt,name=sound,proto3" json:"sound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequestPb_Content) Reset() {
	*x = NotificationRequestPb_Content{}
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequestPb_Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequestPb_Content) ProtoMessage() {}

func (x *NotificationRequestPb_Content) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequestPb_Content.ProtoReflect.Descriptor instead.
func (*NotificationRequestPb_Content) Descriptor() ([]byte, []int) {
	return file_src_types_notification_v1_notification_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NotificationRequestPb_Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationRequestPb_Content) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationRequestPb_Content) GetSound() string {
	if x != nil {
		return x.Sound
	}
	return ""
}

var File_src_types_notification_v1_notification_proto protoreflect.FileDescriptor

const file_src_types_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	",src/types/notification/v1/notification.proto\x12\x19src.types.notification.v1\"_\n" +
	"\x15WebPushSubscriptionPb\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06p256dh\x18\x02 \x01(\tR\x06p256dh\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\tR\x04auth\"\xff\x02\n" +
	"\x15NotificationRequestPb\x12!\n" +
	"\frecipient_id\x18\x01 \x01(\tR\vrecipientId\x12R\n" +
	"\acontent\x18\x02 \x01(\v28.src.types.notification.v1.NotificationRequestPb.ContentR\acontent\x12d\n" +
	"\fdata_payload\x18\x03 \x03(\v2A.src.types.notification.v1.NotificationRequestPb.DataPayloadEntryR\vdataPayload\x1aI\n" +
	"\aContent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x14\n" +
	"\x05sound\x18\x03 \x01(\tR\x05sound\x1a>\n" +
	"\x10DataPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\rDeviceTokenPb\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatformBQZOgithub.com/tinywideclouds/gen-platform/go/types/notification/v1;notification_v1b\x06proto3"

var (
	file_src_types_notification_v1_notification_proto_rawDescOnce sync.Once
	file_src_types_notification_v1_notification_proto_rawDescData []byte
)

func file_src_types_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_src_types_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_src_types_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_notification_v1_notification_proto_rawDesc), len(file_src_types_notification_v1_notification_proto_rawDesc)))
	})
	return file_src_types_notification_v1_notification_proto_rawDescData
}

var file_src_types_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_types_notification_v1_notification_proto_goTypes = []any{
	(*WebPushSubscriptionPb)(nil),         // 0: src.types.notification.v1.WebPushSubscriptionPb
	(*NotificationRequestPb)(nil),         // 1: src.types.notification.v1.NotificationRequestPb
	(*DeviceTokenPb)(nil),                 // 2: src.types.notification.v1.DeviceTokenPb
	(*NotificationRequestPb_Content)(nil), // 3: src.types.notification.v1.NotificationRequestPb.Content
	nil,                                   // 4: src.types.notification.v1.NotificationRequestPb.DataPayloadEntry
}
var file_src_types_notification_v1_notification_proto_depIdxs = []int32{
	3, // 0: src.types.notification.v1.NotificationRequestPb.content:type_name -> src.types.notification.v1.NotificationRequestPb.Content
	4, // 1: src.types.notification.v1.NotificationRequestPb.data_payload:type_name -> src.types.notification.v1.NotificationRequestPb.DataPayloadEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_types_notification_v1_notification_proto_init() }
func file_src_types_notification_v1_notification_proto_init() {
	if File_src_types_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_notification_v1_notification_proto_rawDesc), len(file_src_types_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_src_types_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_src_types_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_src_types_notification_v1_notification_proto = out.File
	file_src_types_notification_v1_notification_proto_goTypes = nil
	file_src_types_notification_v1_notification_proto_depIdxs = nil
}
